# Generated by Django 5.2.7 on 2025-11-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_api', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('set_id', models.CharField(blank=True, max_length=255, null=True)),
                ('set_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
                ('especial_type', models.CharField(blank=True, max_length=255, null=True)),
                ('trainer', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCarta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokeApiCore.carta', to_field='id_api')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokeApiCore.usuario', to_field='nombre')),
            ],
            options={
                'unique_together': {('usuario', 'carta')},
            },
        ),
    ]
